
position_dim: 3
use_physics_features: ${trainer.use_physics_features}
domains:
  surface:
    output_dims:
      pressure: 1
    feature_dim:
      surface_sdf: 1
      surface_normals: 3
  volume:
    output_dims:
      velocity: 3
    feature_dim:
      volume_sdf: 1
      volume_normals: 3
