kind: noether.modeling.models.AeroABUPT
name: ab_upt
geometry_depth: 1
hidden_dim: 192
supernode_pooling_config:
  input_dim: ${data_specs.position_dim}
  k: 32
transformer_block_config:
  num_heads: 3
  mlp_expansion_factor: 4
  use_rope: true
physics_blocks:
  - perceiver
  - self
  - self
  - self
  - self
  - self
num_domain_decoder_blocks:
  volume: 2
optimizer_config: ${optimizer}
forward_properties:
  - volume_anchor_position
  - simulation_parameters
  - geometry_position
  - geometry_batch_idx
  - geometry_supernode_idx
data_specs: ${data_specs}
