# @package _global_

dataset_kind: boilerplate_project.datasets.BaseDataset

defaults:
  - model: base_model
  - datasets: base_dataset
  - tracker: base_tracker
  - callbacks: base_callback
  - trainer: base_trainer
  - optim: adamw 
  - _self_

output_path: ./outputs